"""Generate docs/API.md from the public names and signatures of each module.

Run from the repository root:  PYTHONPATH=src python3 tools/gen_api.py
"""
from __future__ import annotations

import importlib
import inspect
from pathlib import Path

MODULES = [
    ("finlab.cv", "Cross-validation (AFML ch. 7)"),
    ("finlab.bars", "Financial data structures (AFML ch. 2)"),
    ("finlab.labeling", "Labeling (AFML ch. 3)"),
    ("finlab.weights", "Sample weights (AFML ch. 4)"),
    ("finlab.monte_carlo", "Monte Carlo experiments (AFML ch. 4)"),
    ("finlab.fracdiff", "Fractionally differentiated features (AFML ch. 5)"),
    ("finlab.ensemble", "Ensemble methods (AFML ch. 6)"),
    ("finlab.importance", "Feature importance (AFML ch. 8)"),
    ("finlab.tuning", "Hyper-parameter tuning (AFML ch. 9)"),
    ("finlab.bet_sizing", "Bet sizing (AFML ch. 10)"),
    ("finlab.pbo", "Backtest overfitting via CSCV (AFML ch. 11)"),
    ("finlab.stats", "Backtest statistics (AFML ch. 14)"),
    ("finlab.trials", "Trial records that feed PBO and deflated Sharpe (not AFML; feeds ch. 11 and 14)"),
    ("finlab.plot", "Plotly figures for PBO, deflated Sharpe and the Monte Carlo experiment (optional extra)"),
    ("finlab.hrp", "Hierarchical risk parity (AFML ch. 16)"),
    ("finlab.structural_breaks", "Structural breaks (AFML ch. 17)"),
    ("finlab.entropy", "Entropy features (AFML ch. 18)"),
    ("finlab.microstructure", "Microstructure features (AFML ch. 19)"),
    ("finlab.parallel", "Multiprocessing helpers (AFML ch. 20)"),
    ("finlab.agent.tools", "Agent tool registry (MCP server, see docs/AGENTS.md)"),
]


def _first_line(doc: str | None) -> str:
    if not doc:
        return ""
    return inspect.cleandoc(doc).splitlines()[0]


def main() -> None:
    out = [
        "# finlab API reference",
        "",
        "Generated by `tools/gen_api.py` from each module's `__all__`, signatures and",
        "docstrings. Do not edit by hand; rerun the generator instead.",
        "",
    ]
    for mod_name, title in MODULES:
        mod = importlib.import_module(mod_name)
        names = getattr(mod, "__all__", [])
        out += [f"## `{mod_name}`", "", title, ""]
        for name in names:
            obj = getattr(mod, name)
            if inspect.isclass(obj):
                try:
                    sig = str(inspect.signature(obj))
                except (TypeError, ValueError):
                    sig = "(...)"
                kind = "class"
            elif callable(obj):
                try:
                    sig = str(inspect.signature(obj))
                except (TypeError, ValueError):
                    sig = "(...)"
                kind = "function"
            else:
                sig, kind = "", "constant"
            summary = _first_line(getattr(obj, "__doc__", ""))
            out.append(f"- **`{name}{sig if kind != 'constant' else ''}`** ({kind}). {summary}")
        out.append("")
    path = Path(__file__).resolve().parents[1] / "docs" / "API.md"
    path.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
